# Generated by Django 3.1.1 on 2020-09-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comments_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='picture',
            new_name='image',
        ),
    ]
