# Generated by Django 3.1.1 on 2020-09-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currprice',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highestbid', to='auctions.bid'),
        ),
    ]
