# Generated by Django 3.1.1 on 2020-09-06 19:53

import auctions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200906_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currprice',
            field=models.OneToOneField(blank=True, default=auctions.models.Bid, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highestbid', to='auctions.bid'),
        ),
    ]
